name: "bce-category-embedding-1"
demographics_file: "./data/demographicData/csv/data_world/us_city_demographics.csv"
demographics_normalized_file: "./data/demographicData/csv/census_est_all_data_2019/county_ethnicity_fractions_2019.csv"
embeddings_file: "./data/embeddings/name_category_embeddings.csv"
lr: 1e-5
weight_decay: 1e-4 # 1e-5 for MSE, 1e-4 for BCEWithLogits
loss: "BCEWithLogits" # 'MSE' or 'BCEWithLogits'
restaurant_data_source: "Bing"
hidden_layer_size: 512
num_epochs: 7000
